   # simple NEURAL NETWORK

In [6]:
import numpy as np

In [19]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derrivative(x):
    return x * (1 - x)


training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])
training_outputs = np.array([[0,1,1,0]]).T

np.random.seed(1)
synaptic_weights = 2 * np.random.random((3,1)) -1
print('random starting synaptic weights are: ')
print(synaptic_weights)

for iteration in range(100000):
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    err = training_outputs - outputs
    adjustments = err * sigmoid_derrivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)
    pass
print ('synaptic weights after training are: ')
print (synaptic_weights)
print('outputs after training: ')
print(outputs)
    

random starting synaptic weights are: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
synaptic weights after training are: 
[[12.00870061]
 [-0.2044116 ]
 [-5.8002822 ]]
outputs after training: 
[[0.00301758]
 [0.99753723]
 [0.99799161]
 [0.00246109]]
